      CLASS
            NAME 'piutang'
            EXPRESSION '0'
            STYLE
              SIZE 1
              COLOR 255 0 0
              OUTLINECOLOR 0 0 0
              MAXSCALEDENOM 15000
              OPACITY 20
            END
            
            LABEL
              TYPE TRUETYPE
              FONT vera_sans
              SIZE 8
              ANTIALIAS TRUE
              COLOR 0 0 0
              OUTLINECOLOR 0 255 0
              BUFFER 4
              MINFEATURESIZE auto
              PARTIALS FALSE
              POSITION cc
            END            
        END
        CLASS
            NAME 'lunas'
            EXPRESSION '1'
            STYLE
              SIZE 1
              COLOR 0 255 0
              OUTLINECOLOR 0 0 0
              MAXSCALEDENOM 15000
              OPACITY 20
            END
            
            LABEL
              TYPE TRUETYPE
              FONT vera_sans
              SIZE 8
              ANTIALIAS TRUE
              COLOR 0 0 0
              OUTLINECOLOR 0 255 0
              BUFFER 4
              MINFEATURESIZE auto
              PARTIALS FALSE
              POSITION cc
            END            
        END
        CLASS
            NAME 'batal'
            EXPRESSION '2'
            STYLE
              SIZE 1
              COLOR 255 255 0
              OUTLINECOLOR 0 0 0
              MAXSCALEDENOM 15000
              OPACITY 20
            END
            
            LABEL
              TYPE TRUETYPE
              FONT vera_sans
              SIZE 8
              ANTIALIAS TRUE
              COLOR 0 0 0
              OUTLINECOLOR 0 255 0
              BUFFER 4
              MINFEATURESIZE auto
              PARTIALS FALSE
              POSITION cc
            END            
        END     
        CLASS
            NAME 'no-data'
            EXPRESSION '9'
            STYLE
              SIZE 1
              COLOR 0 0 255
              OUTLINECOLOR 0 0 0
              MAXSCALEDENOM 15000
              OPACITY 20
            END
            
            LABEL
              TYPE TRUETYPE
              FONT vera_sans
              SIZE 8
              ANTIALIAS TRUE
              COLOR 0 0 0
              OUTLINECOLOR 0 255 0
              BUFFER 4
              MINFEATURESIZE auto
              PARTIALS FALSE
              POSITION cc
            END            
        END     